import Link from 'next/link';
import { STYLES } from '@/components/ReportDecoded';

export const metadata = {
  title: 'Terms of Service — Report Decoded',
  description: 'The terms governing your use of Report Decoded — buyer subscriptions, agent subscriptions, refunds, and acceptable use.',
  alternates: {
    canonical: 'https://www.reportdecoded.com.au/terms',
  },
};

export default function TermsPage() {
  return (
    <>
      <style>{STYLES}</style>
      <nav className="nav">
        <Link href="/" style={{ display: 'flex', alignItems: 'center', textDecoration: 'none' }}>
          <img src="/logo-dark.png" alt="Report Decoded" width={180} height={42} style={{ height: 36, width: 'auto' }} />
        </Link>
        <div className="nav-links">
          <Link href="/" className="nav-link" style={{ textDecoration: 'none' }}>
            ← Home
          </Link>
        </div>
      </nav>

      <main style={{ maxWidth: 760, margin: '48px auto', padding: '0 24px', color: 'var(--text)', lineHeight: 1.7 }}>
        <h1 style={{ fontFamily: "var(--font-serif),serif", fontSize: 40, marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ color: 'var(--muted)', marginBottom: 32 }}>Last updated: 22 May 2026</p>

        <h2 style={{ marginTop: 28, marginBottom: 10 }}>1. What we do</h2>
        <p>
          Report Decoded uses AI to interpret Australian building and pest inspection
          reports prepared under AS4349.1. We extract defects, estimate repair costs in
          AUD, recommend negotiation language or builder-rectification language, and
          suggest local tradespeople.
        </p>
        <p>
          <strong>Pricing.</strong> Individual buyer reports are $39 each (one-off, no
          subscription). Buyer's agents and selling agents can subscribe for ongoing
          access on either the Starter plan ($79/month, 12 reports included) or the Pro
          plan ($149/month, unlimited reports plus the agent dashboard, priority support,
          and white-label PDFs branded with the agency's logo and accent colour).
          Subscription terms are in section 4 below.
        </p>

        <h2 style={{ marginTop: 28, marginBottom: 10 }}>2. This is not professional advice</h2>
        <p>
          Our analysis is for general information only. It is generated by an AI model
          (Anthropic's Claude) reading a PDF and may contain errors, omissions, or
          misinterpretations. Repair-cost estimates are indicative only and based on
          general Australian tradie rates as of 2026 — not bound to your specific property.
          <strong> Always consult a licensed builder, building inspector, conveyancer,
          and/or lawyer before making any purchase, payment, or contractual decision.</strong>
          {' '}Report Decoded is not a substitute for any of these professionals.
        </p>

        <h2 style={{ marginTop: 28, marginBottom: 10 }}>3. Refunds</h2>
        <p>
          If our system cannot extract a meaningful analysis from your PDF — for example
          because the file is a scanned image rather than text-based, or is not an
          AS4349.1 inspection report at all — we will automatically refund your payment.
        </p>
        <p>
          We do not refund for analyses we have successfully delivered, regardless of
          whether you proceed with the property purchase. If you believe an analysis is
          substantively wrong, email us at{' '}
          <a href="mailto:info@reportdecoded.com.au" style={{ color: 'var(--amber)' }}>
            info@reportdecoded.com.au
          </a>
          {' '}and we will review your case in good faith.
        </p>

        <h2 style={{ marginTop: 28, marginBottom: 10 }}>4. Agent subscriptions</h2>
        <p>
          Buyer's agents and selling agents may subscribe for ongoing access:
        </p>
        <ul style={{ paddingLeft: 24 }}>
          <li>
            <strong>Starter ($79/month):</strong> includes 12 reports per calendar month.
            Additional reports above the monthly quota are billed at $15 each via
            metered Stripe billing in the same monthly invoice.
          </li>
          <li>
            <strong>Pro ($149/month):</strong> unlimited reports, plus the agent
            dashboard, priority support, and white-label PDFs branded with your
            agency.
          </li>
          <li>
            Subscriptions auto-renew monthly on the same date as sign-up. You authorise
            us (via Stripe) to charge your nominated payment method each billing cycle.
          </li>
          <li>
            You can cancel at any time from your dashboard or by emailing us. Cancellation
            takes effect at the end of the current billing period; you retain access
            until then.
          </li>
          <li>
            No refunds are issued for partial months or for unused report quota. If
            Stripe is unable to charge your card, your subscription will be paused until
            you update your billing method.
          </li>
          <li>
            New agents are given a Stripe trial that ends the moment you upload your
            first completed report — meaning you are not billed until you have used the
            service. Trial terms are set at Stripe checkout.
          </li>
          <li>
            We may change pricing with at least 30 days written notice to your registered
            email address. Existing subscribers continue at their current rate until the
            next renewal after the notice period ends.
          </li>
        </ul>

        <h2 style={{ marginTop: 28, marginBottom: 10 }}>5. Negotiation letters and rectification letters</h2>
        <p>
          Where your analysis includes an auto-generated negotiation letter (pre-purchase
          reports) or builder rectification letter (new-build handover reports), these
          are <strong>drafted templates intended as a starting point</strong>. They are
          not legal correspondence and have not been reviewed by a solicitor.
        </p>
        <p>
          Before sending any generated letter to a vendor, vendor's agent, builder, or
          other party, you should: (a) review the letter for factual accuracy against
          your inspection report; (b) adjust the wording to suit your tone, context,
          and relationship with the recipient; and (c) seek legal advice if you are
          unsure about phrasing that could affect your contractual position. Report
          Decoded is not responsible for the outcome of any communication you send
          based on a template we have generated.
        </p>

        <h2 style={{ marginTop: 28, marginBottom: 10 }}>6. Tradesperson suggestions</h2>
        <p>
          Tradies shown in your report are sourced from public business listings via HERE
          Maps. They are not endorsed, vetted, employed, or warranted by Report Decoded.
          You engage any tradesperson at your own risk. Always verify their licence,
          insurance, references, and quotes independently.
        </p>

        <h2 style={{ marginTop: 28, marginBottom: 10 }}>7. Your data</h2>
        <p>
          Our handling of your data is covered by our{' '}
          <Link href="/privacy" style={{ color: 'var(--amber)' }}>
            Privacy Policy
          </Link>
          . By using the service you consent to that handling.
        </p>

        <h2 style={{ marginTop: 28, marginBottom: 10 }}>8. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by Australian law, Report Decoded is not liable
          for any indirect, incidental, or consequential loss arising from your use of the
          service, including but not limited to property-purchase decisions you make based
          on our analysis. Our total liability in any matter is capped at the amount you
          paid us for the report in question (i.e. $39 per single report).
        </p>
        <p>
          Nothing in these terms excludes the consumer guarantees under the Australian
          Consumer Law (Schedule 2 of the Competition and Consumer Act 2010 (Cth)) which
          cannot be lawfully excluded.
        </p>

        <h2 style={{ marginTop: 28, marginBottom: 10 }}>9. Acceptable use</h2>
        <p>
          You may use Report Decoded only for your own property purchasing or management
          decisions, or those of clients you represent. You may not redistribute, resell,
          or commercialise the output of our service without a written agreement with us.
        </p>

        <h2 style={{ marginTop: 28, marginBottom: 10 }}>10. Governing law</h2>
        <p>
          These terms are governed by the laws of Victoria, Australia. Any dispute is
          subject to the non-exclusive jurisdiction of the courts of Victoria.
        </p>

        <h2 style={{ marginTop: 28, marginBottom: 10 }}>11. Contact</h2>
        <p>
          <a href="mailto:info@reportdecoded.com.au" style={{ color: 'var(--amber)' }}>
            info@reportdecoded.com.au
          </a>
        </p>

        <p style={{ marginTop: 48, color: 'var(--muted)', fontSize: 13 }}>
          This page is a plain-English starter and should be reviewed by an Australian
          lawyer before public launch. We will refine it as the product evolves.
        </p>
      </main>
    </>
  );
}
