// lib/articles.js
//
// Registry of /resources/{slug} long-form articles. Used by:
//   • app/resources/page.js — index listing
//   • app/sitemap.js — auto-add to sitemap
//   • internal cross-links between articles
//
// Each article's actual body content lives in app/resources/{slug}/page.js
// (it's JSX, not data). This file just keeps metadata in one place.

export const ARTICLES = [
  {
    slug: 'what-is-as4349-1',
    title: 'What is AS4349.1? The Australian Standard for Building Inspections, Explained',
    description: 'Plain-English breakdown of Australian Standard AS4349.1 — what it covers, what it doesn\'t, how to read the report, and what to do next.',
    category: 'Buyer guide',
    published: '2026-05-20',
    updated: '2026-05-20',
    readTime: '6 min',
    excerpt: 'Every Australian pre-purchase building inspection is meant to be done to AS4349.1. Most buyers have no idea what that standard actually requires — or what it leaves out.',
  },
  {
    slug: 'how-much-to-negotiate-after-building-inspection',
    title: 'How Much Should I Negotiate After a Building Inspection? (Real Australian Numbers)',
    description: 'A practical framework + benchmark dollar ranges for negotiating off contract price after your AS4349.1 building inspection comes back.',
    category: 'Buyer guide',
    published: '2026-05-20',
    updated: '2026-05-20',
    readTime: '8 min',
    excerpt: 'Your building inspection came back. There are issues. Now what? Here\'s how Australian buyers turn defect lists into defensible dollar amounts off the price.',
  },
  {
    slug: 'termite-damage-cost-australia',
    title: 'Termite Damage Cost to Repair in Australia: What Buyers Should Budget',
    description: 'How much it costs to repair termite damage in Australian homes — by damage extent, by trade, by state, with realistic ranges from real inspection reports.',
    category: 'Buyer guide',
    published: '2026-05-20',
    updated: '2026-05-20',
    readTime: '7 min',
    excerpt: 'Termites cause more property damage in Australia than fire, flood, and storms combined. If your inspection finds termite evidence, the cost question depends on five things.',
  },
  {
    slug: 'asbestos-australian-homes-buyer-guide',
    title: 'Asbestos in Australian Homes: What Building Inspections Catch and What They Miss',
    description: 'Plain-English guide to asbestos in Australian houses — where it hides, what inspectors can and can\'t identify, removal costs, and when it\'s safe to leave alone.',
    category: 'Buyer guide',
    published: '2026-05-21',
    updated: '2026-05-21',
    readTime: '8 min',
    excerpt: 'About 1 in 3 Australian homes built before 1990 contains asbestos somewhere. Your building inspection will flag visual indicators but can\'t confirm without lab testing. Here\'s what that actually means for buyers.',
  },
  {
    slug: 'practical-completion-inspection-australia',
    title: 'New-Build Practical Completion Inspection (PCI): The Australian Buyer\'s Guide',
    description: 'What a PCI covers, when to do it, the Defects Liability Period, builder rectification rights, and how to use the inspection to hold the builder accountable.',
    category: 'Buyer guide',
    published: '2026-05-21',
    updated: '2026-05-21',
    readTime: '9 min',
    excerpt: 'Your new-build is almost done. The builder wants you to sign off on Practical Completion. This is the most important inspection you\'ll commission as a new-build buyer — and the only chance to require builder rectification before final payment.',
  },
  {
    slug: 'rising-damp-australia-how-much-to-fix',
    title: 'Rising Damp in Australia: How Much It Actually Costs to Fix in 2026',
    description: 'Real Australian rising damp (and salt damp) repair costs — chemical DPC injection, mechanical replacement, replastering, and what your building inspector\'s "rising damp evident" note actually means for your wallet.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-08-10',
    readTime: '8 min',
    excerpt: 'If your building inspection report uses the phrase "evidence of rising damp," "efflorescence to lower courses," or "elevated moisture meter readings at floor level" — you\'re looking at a repair bill that can range from $4,000 to over $40,000. Here\'s how to tell which end of that range your property sits at.',
  },
  {
    slug: 'what-to-do-if-building-inspection-finds-major-problems',
    title: 'What to Do If Your Building Inspection Finds Major Problems (Australia, 2026)',
    description: 'A step-by-step decision framework for Australian buyers whose pre-purchase inspection has come back with serious defects — how to triage, cost, negotiate, walk away, or proceed with confidence.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '9 min',
    excerpt: 'The report just landed. There are red flags. Cooling-off ends in days. Here\'s exactly what to do — in what order — to turn an alarming inspection report into either a defensible price drop, a clean walk-away, or a confident proceed.',
  },
  {
    slug: 'building-inspection-vs-pest-inspection-difference',
    title: 'Building Inspection vs Pest Inspection: What\'s the Difference in Australia?',
    description: 'Plain-English breakdown of the two AS4349 inspections every Australian buyer needs — what each covers, what they miss, why you need both, and how much each actually costs.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '7 min',
    excerpt: 'Your conveyancer told you to get "a building and pest inspection." Most buyers assume that\'s one document. It\'s actually two completely different inspections done to two different Australian Standards — and skipping the second one is the most expensive mistake AU buyers make.',
  },
  {
    slug: 'cooling-off-period-building-inspection-rights-by-state',
    title: 'Cooling-Off Period Building Inspection Rights by State (Australia, 2026)',
    description: 'State-by-state guide to your cooling-off rights as an Australian property buyer — VIC, NSW, QLD, SA, WA, ACT, TAS, NT. When the clock starts, what you can do inside it, when you can\'t walk away, and how the building inspection fits.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '10 min',
    excerpt: 'You just signed the contract. The agent says the cooling-off period started today. Your building inspector is booked for Tuesday. Will the report come back in time? What happens if it\'s bad? Here\'s exactly what your rights are, state by state.',
  },
  {
    slug: 'section-32-vendor-statement-building-inspection-victoria',
    title: 'Section 32 Vendor Statement and Your Building Inspection (Victoria, 2026)',
    description: 'What the Victorian Section 32 vendor statement legally must contain, how it interacts with your AS4349.1 building inspection, the most common omissions and gotchas, and what to do if you find a defect that should have been disclosed.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '11 min',
    excerpt: 'Every Victorian property sale comes with a Section 32 — a mandatory pre-contract vendor disclosure document. Most buyers receive it, skim it, and sign. Inside the 30-100 pages are the items that could give you legal grounds to rescind without penalty, regardless of cooling-off — IF you know what to look for.',
  },
  {
    slug: 'buyers-agent-technical-due-diligence-tools-2026',
    title: 'Buyer\'s Agent Technical Due Diligence Tools (Australia, 2026)',
    description: 'The complete AU buyer\'s agent tech stack for technical due diligence in 2026 — property data, title and planning, building and pest, strata reports, AI report analysis, CRM. Honest categorised breakdown with pricing.',
    category: 'For buyer\'s agents',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '13 min',
    excerpt: 'You\'re doing 8–15 property due diligence assessments a week. Your time is the constraint. Here\'s the 2026 Australian buyer\'s agent tech stack that compresses property research from 4 hours to 45 minutes — categorised by what each tool does, what it costs, and where it actually moves the needle.',
  },
  {
    slug: 'white-label-building-inspection-report-for-buyers-agents',
    title: 'White-Label Building Inspection Reports for Buyer\'s Agents (Australia, 2026)',
    description: 'How AU buyer\'s agents can deliver branded AS4349.1 building inspection analysis to their clients — what white-label means in property context, what can be branded, what it costs, common pitfalls, and how to set it up.',
    category: 'For buyer\'s agents',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '9 min',
    excerpt: 'Your client uploads their building inspection PDF. Two minutes later they receive a polished defect-by-defect breakdown — with YOUR logo on it, YOUR accent colour, YOUR brand voice. Here\'s how white-label property reports work in 2026, what they cost, and where most agents get the setup wrong.',
  },
  {
    slug: 'lead-paint-pre-1970-australian-homes-buyer-guide',
    title: 'Lead Paint in Pre-1970 Australian Homes: What Building Inspections Catch and What They Miss',
    description: 'Plain-English guide to lead paint in Australian houses built before 1970 — health risk, where it hides, what AS4349.1 inspectors can and can\'t identify, when to test, and remediation costs.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '8 min',
    excerpt: 'About 70% of Australian homes built before 1970 contain lead paint somewhere. Your building inspection may flag suspicious paint, but can\'t confirm without lab testing. Most buyers don\'t test — and then renovate without knowing. Here\'s what the actual risk is, what testing costs, and when you should bother.',
  },
  {
    slug: 'how-to-write-builder-rectification-letter-australia',
    title: 'How to Write a Builder Rectification Letter (Australia, 2026) — With Template',
    description: 'Step-by-step guide for Australian new-build owners writing a defects rectification letter to their builder during DLP or PCI. Includes a full ready-to-use template you can copy, edit, and send.',
    category: 'New build',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '10 min',
    excerpt: 'You\'ve identified defects in your new build during practical completion or the defects liability period. The builder is dragging their feet. The fix is a written rectification letter — done correctly, it triggers contractual obligations the builder can\'t ignore. Here\'s the structure that works, plus a full template you can copy.',
  },
  {
    slug: 'strata-report-explained-australia',
    title: 'Strata Report Explained: The Australian Apartment Buyer\'s Guide (2026)',
    description: 'Plain-English breakdown of strata reports / OC certificates / S184 certificates for Australian apartment and unit buyers — what\'s in one, what to look for, state-by-state naming, costs, red flags, and what they don\'t cover.',
    category: 'Buyer guide',
    published: '2026-05-31',
    updated: '2026-05-31',
    readTime: '11 min',
    excerpt: 'You\'re buying an apartment, townhouse, or unit in Australia. Your conveyancer says you need a "strata report." In Victoria it\'s called an Owners Corporation certificate. In NSW it\'s a Section 184 certificate plus a strata records inspection. Most buyers skim it and miss the levy bombshell sitting on page 23. Here\'s exactly what\'s in one, what to look for, and where it falls short.',
  },
  {
    slug: 'concrete-cancer-spalling-cost-australia',
    title: 'Concrete Cancer Repair Cost in Australia: Severity Levels & 2026 Prices',
    description: 'What concrete cancer (concrete spalling) actually costs to repair in Australia — the repair process step by step, severity levels, real 2026 repair costs by scenario for houses and apartments, and when to negotiate vs walk away.',
    category: 'Buyer guide',
    published: '2026-05-31',
    updated: '2026-08-10',
    readTime: '9 min',
    excerpt: 'Your building inspector wrote "concrete cancer evident to balcony slab" and you stopped reading. It sounds catastrophic. Most of the time it isn\'t — but the cost difference between a cosmetic patch and a structural repair is roughly $3,000 vs $80,000. Here\'s how to tell which one you\'re looking at.',
  },
  {
    slug: 'mould-in-australian-homes-remediation-cost',
    title: 'Mould in Australian Homes: Remediation Cost and What Inspections Miss (2026)',
    description: 'Plain-English guide to mould in Australian houses and apartments — health risk, where it hides, why surface cleaning fails, real remediation costs by severity, and what your AS4349.1 building inspection actually catches.',
    category: 'Buyer guide',
    published: '2026-05-31',
    updated: '2026-05-31',
    readTime: '9 min',
    excerpt: 'Your inspector flagged "mould evident to bathroom ceiling." You\'re wondering if it\'s a deal-breaker or a $300 fix. The honest answer: it depends entirely on the root cause behind it. Visible mould is a symptom — the real question is what\'s feeding it. Here\'s how to triage, what testing costs, and what remediation actually involves.',
  },
  {
    slug: 'pre-auction-building-inspection-australia',
    title: 'Pre-Auction Building Inspection in Australia: The 2026 Buyer\'s Guide',
    description: 'Why pre-auction inspection is non-negotiable (no cooling-off applies), what it costs, how to handle 3-5 properties in a campaign, whether to trust vendor-prepared reports, and the auction-day decision framework.',
    category: 'Buyer guide',
    published: '2026-05-31',
    updated: '2026-05-31',
    readTime: '10 min',
    excerpt: 'Auction contracts have no cooling-off period in any Australian state. The hammer falls, the contract is unconditional, and any defect you didn\'t discover beforehand is now yours to fund. Here\'s how to inspect properly when you might be bidding on 3-5 properties across a campaign, what vendor-prepared reports are worth, and how to read findings against a 48-hour decision clock.',
  },
  {
    slug: 'hidden-costs-buying-house-australia-2026',
    title: 'Hidden Costs of Buying a House in Australia (2026): The Full Stack',
    description: 'Every cost beyond the deposit when you buy property in Australia — stamp duty by state, conveyancing, building & pest, strata report, LMI, loan fees, insurance, settlement disbursements. Real 2026 dollar ranges, no fluff.',
    category: 'Buyer guide',
    published: '2026-06-05',
    updated: '2026-06-05',
    readTime: '12 min',
    excerpt: 'You\'ve saved the deposit. You think you\'re ready. Then the conveyancer mentions $1,600 in disbursements you hadn\'t budgeted for, the inspection comes in at $750, stamp duty is $14k higher than the calculator said, and the lender wants $1,295 for the valuation. Add it up and most Australian buyers spend $8,000-$15,000 BEYOND the deposit before they have the keys. Here\'s the full stack — every line item, what it actually costs in 2026 dollars, and which ones you can negotiate.',
  },
  {
    slug: 'perth-building-inspection-wa-buyer-guide',
    title: 'Perth Building Inspection: The WA Buyer\'s Playbook (2026)',
    description: 'WA-specific building inspection guide for Perth and Western Australian property buyers — jarrah white ant risk, sand-foundation movement, coastal salt damage, WA cooling-off particularities, and what AS4349.1 covers differently west of the Nullarbor.',
    category: 'Buyer guide',
    published: '2026-06-05',
    updated: '2026-06-05',
    readTime: '9 min',
    excerpt: 'Perth building stock has problems East Coast inspectors rarely see — jarrah white ants instead of subterranean termites, sand-base reactive movement instead of clay, salt damage from coastal exposure, and Hardies sheeting that often pre-dates 1987 asbestos cutoffs. Plus WA has no statutory cooling-off — your only protection is the inspection clause you negotiate into the contract before signing. Here\'s the WA-specific playbook.',
  },
  {
    slug: 'building-inspection-negotiation-letter-template-australia',
    title: 'Building Inspection Negotiation Letter Template (Australia) — With State Examples',
    description: 'Plain-English guide for Australian buyers writing a negotiation letter to the vendor after a building inspection comes back with defects. Letter structure that works, what NOT to include, plus full ready-to-use sample letters for VIC, NSW, and QLD.',
    category: 'Buyer guide',
    published: '2026-06-05',
    updated: '2026-06-05',
    readTime: '11 min',
    excerpt: 'Your building inspection has come back with $34,000 of defects. You\'re in cooling-off. You have one shot at a written negotiation letter that either gets you the price reduction or gets you a clean exit. Most buyers send vague "can we knock something off" emails that get rejected. The vendors who say YES are the ones who received a specific, evidence-anchored letter quoting findings to inspector page numbers. Here\'s the structure that works, plus full sample letters for VIC, NSW, and QLD.',
  },
  {
    slug: 'how-fast-book-building-inspection-australia',
    title: 'How Fast Can You Book a Building Inspection in Australia? (2026)',
    description: 'Real turnaround times for Australian building inspections — standard 5-10 day window, expedited 24-48 hour, same-day premium, weekend bookings, regional surcharges. By city, by scenario (cooling-off, pre-auction, post-contract).',
    category: 'Buyer guide',
    published: '2026-06-05',
    updated: '2026-06-05',
    readTime: '7 min',
    excerpt: 'You just signed a contract. Cooling-off ends in 3 business days. You need a building inspection done, the report written, and time to read it — fast. Most metro AU inspectors can hit a 24-48 hour turnaround for an expedite fee. Some offer same-day. Here\'s realistic timing by city, by scenario, and what the expedite premiums actually cost.',
  },
  {
    slug: 'booking-building-inspection-during-cooling-off-state-by-state',
    title: 'Booking a Building Inspection During Cooling-Off: State-by-State Australia (2026)',
    description: 'How to fit a building inspection inside the cooling-off window in VIC (3 business days), NSW (5 business days), QLD (5 business days), ACT (5 business days), SA (2 business days), WA (no statutory cooling-off), TAS, and NT. Operational guide with realistic timelines.',
    category: 'Buyer guide',
    published: '2026-06-05',
    updated: '2026-06-05',
    readTime: '8 min',
    excerpt: 'You\'ve signed the contract. The agent says cooling-off started. You have 2-5 business days to commission an inspection, get the report, read it, and decide whether to rescind. Each state has its own window and its own practical constraints. Here\'s exactly how to fit the inspection into each state\'s cooling-off period — and what to do when the window is too tight.',
  },
  {
    slug: 'rising-damp-melbourne-suburb-cost-guide',
    title: 'Rising Damp in Melbourne: Cost to Fix by Suburb (2026)',
    description: 'Suburb-specific rising damp repair costs across Melbourne — inner-north terraces (Brunswick, Fitzroy, Northcote), eastern Victorian, bayside (Brighton, Sandringham), western (Yarraville, Footscray). Treatment options, real 2026 dollar ranges, what your inspector\'s report means for your wallet.',
    category: 'Buyer guide',
    published: '2026-06-05',
    updated: '2026-06-05',
    readTime: '8 min',
    excerpt: 'If you\'re buying a pre-1940 Melbourne terrace, your inspector almost certainly flagged rising damp. The cost depends massively on which Melbourne suburb — Brunswick double-brick terraces have different DPC retrofits than weatherboard Yarraville cottages. Here\'s realistic 2026 repair costs by Melbourne suburb cluster, plus when you can defer treatment vs when it must be rectified immediately.',
  },
  {
    slug: 'rising-damp-treatment-cost-sydney',
    title: 'Rising Damp Treatment Cost in Sydney: What to Pay by Suburb (2026)',
    description: 'Suburb-specific rising damp treatment costs across Sydney — inner-city terraces (Paddington, Surry Hills, Newtown, Glebe), inner-west (Balmain, Leichhardt, Marrickville), sandstone cottages, and salt-driven coastal moisture (Bondi, Coogee). Real 2026 dollar ranges, treatment options, and what your inspector\'s report means for negotiation.',
    category: 'Buyer guide',
    published: '2026-08-13',
    updated: '2026-08-13',
    readTime: '8 min',
    excerpt: 'Buying a Victorian or Federation terrace in Sydney\'s inner suburbs? Your inspector almost certainly flagged rising damp — and in Sydney\'s sandstock-brick and sandstone stock the cost to fix swings from a $2,000 cosmetic patch to a $35,000 mechanical DPC retrofit. Here\'s realistic 2026 treatment costs by Sydney suburb cluster, plus how to turn the finding into a negotiation position.',
  },
  {
    slug: 'black-mould-vs-other-mould-australian-homes',
    title: 'Black Mould vs Other Mould in Australian Homes: When to Panic, When to Clean (2026)',
    description: 'Plain-English guide for Australian buyers and homeowners worried about black mould — what stachybotrys chartarum actually is, how common it really is in AU homes, when DIY cleaning is fine, and when you need a Category 3 remediation specialist.',
    category: 'Buyer guide',
    published: '2026-06-05',
    updated: '2026-06-05',
    readTime: '8 min',
    excerpt: '"Black mould" is the panic word in property buyer culture. The actual story: stachybotrys (the "toxic" black mould) is real but less common than media coverage suggests. Many dark mould patches are cladosporium or aspergillus — allergenic but not toxigenic, and DIY-cleanable. Here\'s how to tell the difference, when to test, and when to call a Category 3 remediation specialist.',
  },
  {
    slug: 'how-to-read-as4349-1-inspection-report',
    title: 'How to Read an Australian Building Inspection Report (AS4349.1): A Buyer\'s Guide',
    description: 'Plain-English walkthrough of how an AS4349.1 building inspection report is structured, what each section means, how to interpret inspector terminology (drummy render, spalling, efflorescence, etc.), and how to triage 60-100 pages in under an hour.',
    category: 'Buyer guide',
    published: '2026-06-05',
    updated: '2026-06-05',
    readTime: '10 min',
    excerpt: 'Your building inspector sent you a 60-100 page PDF. The first page is a Statement of Limitations. The second is the Methodology section. By page 8 you\'re reading "drummy render to lower wing wall plaster, monitor for progression" and your eyes glaze over. Here\'s the section-by-section anatomy of an AS4349.1 report, what the technical terminology actually means in plain English, and how to triage the document in under an hour.',
  },
  {
    slug: 'just-got-building-inspection-report-australia',
    title: 'Just Got Your Building Inspection Report? Here\'s What to Do First (Australia)',
    description: 'A step-by-step guide for Australian buyers who have just received their building inspection report — how to triage it fast, what the terminology means, how to get cost estimates the report doesn\'t include, and how to act before cooling-off ends.',
    category: 'Buyer guide',
    published: '2026-06-07',
    updated: '2026-06-07',
    readTime: '8 min',
    excerpt: 'The PDF just landed. It\'s 85 pages. Cooling-off ends in 3 business days. Here\'s the exact sequence — what to read first, what to skip, what the jargon means, how to get cost estimates (the report won\'t include them), and how to turn the findings into a negotiation or a clean walk-away.',
  },
  {
    slug: 'building-inspection-report-no-cost-estimates-australia',
    title: 'Why Your Building Inspection Report Has No Cost Estimates — and How to Get Them',
    description: 'Australian AS4349.1 building inspection reports are legally required to exclude cost estimates. This guide explains why, what your options are for getting repair costs, and how to turn a defect list into a dollar figure you can negotiate with.',
    category: 'Buyer guide',
    published: '2026-06-07',
    updated: '2026-06-07',
    readTime: '7 min',
    excerpt: 'Your building report lists 14 defects and not a single dollar figure. That\'s not an oversight — AS4349.1 and the NSW Government\'s own guidance confirms standard reports are not required to include cost estimates. Here\'s why that rule exists, and your three options for getting the cost data you actually need to negotiate.',
  },
  {
    slug: 'what-does-average-condition-mean-building-inspection',
    title: 'What Does "Average Condition" Mean on an Australian Building Inspection Report?',
    description: 'If your Australian building inspection report says the property is in "average condition," this guide explains exactly what that means, what it doesn\'t mean, and whether you should be worried.',
    category: 'Buyer guide',
    published: '2026-06-07',
    updated: '2026-06-07',
    readTime: '6 min',
    excerpt: '"Average condition" on an Australian building inspection report does NOT mean the property is safe to buy without negotiation — but it also doesn\'t mean it\'s a disaster. Here\'s what the rating actually means, how inspectors apply it, and what you should do next depending on which defects pushed the property into the "average" band.',
  },
  {
    slug: 'structural-cracks-building-inspection-australia',
    title: 'Structural Cracks vs Cosmetic Cracks: What Your Building Inspection Is Really Saying (Australia)',
    description: 'How to tell the difference between structural cracks and cosmetic cracks in an Australian building inspection report — what each crack type means, what it costs to repair, and whether it\'s a negotiation trigger or a walk-away.',
    category: 'Buyer guide',
    published: '2026-06-07',
    updated: '2026-06-07',
    readTime: '9 min',
    excerpt: 'Not all cracks are equal. A hairline crack in render costs $200 to patch. A stair-step crack through brickwork to the footing can mean $20,000–$60,000 in underpinning. Your inspector classified it — but the classification alone doesn\'t tell you which end of that range you\'re at. Here\'s how to read crack findings in an Australian building inspection report.',
  },
  {
    slug: 'roof-damage-repair-cost-building-inspection-australia',
    title: 'Roof Damage in Your Building Inspection: Repair Costs and What to Do Next (Australia, 2026)',
    description: 'What different roof defect findings in an Australian building inspection report actually cost to fix — ridge capping, valley iron, sarking, gutters, full re-roof — plus how to use roof findings to negotiate.',
    category: 'Buyer guide',
    published: '2026-06-07',
    updated: '2026-06-07',
    readTime: '8 min',
    excerpt: 'Roof defects are the most common major finding in Australian building inspections — and the most misunderstood. "Roof requires attention" can mean $800 in ridge repointing or $35,000 in a full re-roof. Here\'s how to interpret what your inspector actually found, what it costs to fix, and how to structure a negotiation around it.',
  },
  {
    slug: 'bathroom-waterproofing-failure-building-inspection-australia',
    title: 'Failed Bathroom Waterproofing on Your Building Inspection: Costs and Next Steps (Australia)',
    description: 'What failed bathroom or wet area waterproofing means in an Australian building inspection report — why it\'s so common, what it costs to fix, what\'s behind the tiles you can\'t see, and how to negotiate.',
    category: 'Buyer guide',
    published: '2026-06-07',
    updated: '2026-06-07',
    readTime: '8 min',
    excerpt: 'Failed shower or bathroom waterproofing is one of the most common findings in Australian building inspections — and one of the most deceptive. The surface looks fine. The damage is in the wall and subfloor. Your inspector flagged it; here\'s what it actually means, what it costs to fix ($3,000–$18,000 depending on damage extent), and how to use it in negotiations.',
  },
  {
    slug: 'electrical-safety-building-inspection-australia',
    title: 'Electrical Safety Findings on Your Building Inspection Report: What Australian Buyers Need to Know',
    description: 'What electrical safety defects in an Australian AS4349.1 building inspection report mean — RCDs, smoke alarms, switchboard compliance, unprotected wiring — what they cost to rectify and whether they are a genuine safety risk or a routine fix.',
    category: 'Buyer guide',
    published: '2026-06-07',
    updated: '2026-06-07',
    readTime: '8 min',
    excerpt: 'Electrical findings on an Australian building inspection report range from "no RCD protection — install one for $400" to "unsafe unprotected wiring requires licensed electrician immediately." Your inspector flagged something electrical. Here\'s what each type of finding actually means, what it costs to rectify, and whether it\'s a negotiation point, a safety risk, or just a maintenance item.',
  },
  {
    slug: 'non-compliant-renovations-building-inspection-australia',
    title: 'Non-Compliant Renovations Found in Your Building Inspection: What It Means and What to Do (Australia)',
    description: 'What "non-compliant renovation," "unapproved work," or "no evidence of permit" means in an Australian building inspection report — legal risk, insurance implications, rectification cost, and how to negotiate.',
    category: 'Buyer guide',
    published: '2026-06-07',
    updated: '2026-06-07',
    readTime: '9 min',
    excerpt: 'Your building inspection found a deck, bathroom, or extension with "no evidence of council permit" or "appears non-compliant." This is one of the six defect types with the strongest negotiation leverage in Australian property — but it\'s also one of the most complex. Here\'s what it legally means, what your liability exposure is as a buyer, and how to handle it.',
  },
  {
    slug: 'restumping-reblocking-cost-australia',
    title: 'Restumping & Reblocking Cost in Australia (2026): What It Really Costs',
    description: 'Real Australian restumping and reblocking costs — partial vs full restump, concrete vs galvanised steel stumps, and what "stumps deteriorated" or "floors out of level" in your building inspection actually means for your wallet.',
    category: 'Buyer guide',
    published: '2026-06-17',
    updated: '2026-06-17',
    readTime: '8 min',
    excerpt: 'If your building inspection flags "stumps deteriorated," "subfloor movement," or "floors out of level," you\'re looking at restumping — a bill that runs from $2,000 for a few stumps to $40,000+ for a full reblock. Here\'s how to tell which end of that range you\'re at.',
  },
];

export function allArticleSlugs() {
  return ARTICLES.map((a) => a.slug);
}

export function getArticle(slug) {
  return ARTICLES.find((a) => a.slug === slug) || null;
}
