// lib/articles.js
//
// Registry of /resources/{slug} long-form articles. Used by:
//   • app/resources/page.js — index listing
//   • app/sitemap.js — auto-add to sitemap
//   • internal cross-links between articles
//
// Each article's actual body content lives in app/resources/{slug}/page.js
// (it's JSX, not data). This file just keeps metadata in one place.

export const ARTICLES = [
  {
    slug: 'what-is-as4349-1',
    title: 'What is AS4349.1? The Australian Standard for Building Inspections, Explained',
    description: 'Plain-English breakdown of Australian Standard AS4349.1 — what it covers, what it doesn\'t, how to read the report, and what to do next.',
    category: 'Buyer guide',
    published: '2026-05-20',
    updated: '2026-05-20',
    readTime: '6 min',
    excerpt: 'Every Australian pre-purchase building inspection is meant to be done to AS4349.1. Most buyers have no idea what that standard actually requires — or what it leaves out.',
  },
  {
    slug: 'how-much-to-negotiate-after-building-inspection',
    title: 'How Much Should I Negotiate After a Building Inspection? (Real Australian Numbers)',
    description: 'A practical framework + benchmark dollar ranges for negotiating off contract price after your AS4349.1 building inspection comes back.',
    category: 'Buyer guide',
    published: '2026-05-20',
    updated: '2026-05-20',
    readTime: '8 min',
    excerpt: 'Your building inspection came back. There are issues. Now what? Here\'s how Australian buyers turn defect lists into defensible dollar amounts off the price.',
  },
  {
    slug: 'termite-damage-cost-australia',
    title: 'Termite Damage Cost to Repair in Australia: What Buyers Should Budget',
    description: 'How much it costs to repair termite damage in Australian homes — by damage extent, by trade, by state, with realistic ranges from real inspection reports.',
    category: 'Buyer guide',
    published: '2026-05-20',
    updated: '2026-05-20',
    readTime: '7 min',
    excerpt: 'Termites cause more property damage in Australia than fire, flood, and storms combined. If your inspection finds termite evidence, the cost question depends on five things.',
  },
  {
    slug: 'asbestos-australian-homes-buyer-guide',
    title: 'Asbestos in Australian Homes: What Building Inspections Catch and What They Miss',
    description: 'Plain-English guide to asbestos in Australian houses — where it hides, what inspectors can and can\'t identify, removal costs, and when it\'s safe to leave alone.',
    category: 'Buyer guide',
    published: '2026-05-21',
    updated: '2026-05-21',
    readTime: '8 min',
    excerpt: 'About 1 in 3 Australian homes built before 1990 contains asbestos somewhere. Your building inspection will flag visual indicators but can\'t confirm without lab testing. Here\'s what that actually means for buyers.',
  },
  {
    slug: 'practical-completion-inspection-australia',
    title: 'New-Build Practical Completion Inspection (PCI): The Australian Buyer\'s Guide',
    description: 'What a PCI covers, when to do it, the Defects Liability Period, builder rectification rights, and how to use the inspection to hold the builder accountable.',
    category: 'Buyer guide',
    published: '2026-05-21',
    updated: '2026-05-21',
    readTime: '9 min',
    excerpt: 'Your new-build is almost done. The builder wants you to sign off on Practical Completion. This is the most important inspection you\'ll commission as a new-build buyer — and the only chance to require builder rectification before final payment.',
  },
  {
    slug: 'rising-damp-australia-how-much-to-fix',
    title: 'Rising Damp in Australia: How Much It Actually Costs to Fix in 2026',
    description: 'Real Australian rising damp repair costs — chemical DPC injection, mechanical replacement, replastering, and what your building inspector\'s "rising damp evident" note actually means for your wallet.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '8 min',
    excerpt: 'If your building inspection report uses the phrase "evidence of rising damp," "efflorescence to lower courses," or "elevated moisture meter readings at floor level" — you\'re looking at a repair bill that can range from $4,000 to over $40,000. Here\'s how to tell which end of that range your property sits at.',
  },
  {
    slug: 'what-to-do-if-building-inspection-finds-major-problems',
    title: 'What to Do If Your Building Inspection Finds Major Problems (Australia, 2026)',
    description: 'A step-by-step decision framework for Australian buyers whose pre-purchase inspection has come back with serious defects — how to triage, cost, negotiate, walk away, or proceed with confidence.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '9 min',
    excerpt: 'The report just landed. There are red flags. Cooling-off ends in days. Here\'s exactly what to do — in what order — to turn an alarming inspection report into either a defensible price drop, a clean walk-away, or a confident proceed.',
  },
  {
    slug: 'building-inspection-vs-pest-inspection-difference',
    title: 'Building Inspection vs Pest Inspection: What\'s the Difference in Australia?',
    description: 'Plain-English breakdown of the two AS4349 inspections every Australian buyer needs — what each covers, what they miss, why you need both, and how much each actually costs.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '7 min',
    excerpt: 'Your conveyancer told you to get "a building and pest inspection." Most buyers assume that\'s one document. It\'s actually two completely different inspections done to two different Australian Standards — and skipping the second one is the most expensive mistake AU buyers make.',
  },
  {
    slug: 'cooling-off-period-building-inspection-rights-by-state',
    title: 'Cooling-Off Period Building Inspection Rights by State (Australia, 2026)',
    description: 'State-by-state guide to your cooling-off rights as an Australian property buyer — VIC, NSW, QLD, SA, WA, ACT, TAS, NT. When the clock starts, what you can do inside it, when you can\'t walk away, and how the building inspection fits.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '10 min',
    excerpt: 'You just signed the contract. The agent says the cooling-off period started today. Your building inspector is booked for Tuesday. Will the report come back in time? What happens if it\'s bad? Here\'s exactly what your rights are, state by state.',
  },
  {
    slug: 'section-32-vendor-statement-building-inspection-victoria',
    title: 'Section 32 Vendor Statement and Your Building Inspection (Victoria, 2026)',
    description: 'What the Victorian Section 32 vendor statement legally must contain, how it interacts with your AS4349.1 building inspection, the most common omissions and gotchas, and what to do if you find a defect that should have been disclosed.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '11 min',
    excerpt: 'Every Victorian property sale comes with a Section 32 — a mandatory pre-contract vendor disclosure document. Most buyers receive it, skim it, and sign. Inside the 30-100 pages are the items that could give you legal grounds to rescind without penalty, regardless of cooling-off — IF you know what to look for.',
  },
  {
    slug: 'buyers-agent-technical-due-diligence-tools-2026',
    title: 'Buyer\'s Agent Technical Due Diligence Tools (Australia, 2026)',
    description: 'The complete AU buyer\'s agent tech stack for technical due diligence in 2026 — property data, title and planning, building and pest, strata reports, AI report analysis, CRM. Honest categorised breakdown with pricing.',
    category: 'For buyer\'s agents',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '13 min',
    excerpt: 'You\'re doing 8–15 property due diligence assessments a week. Your time is the constraint. Here\'s the 2026 Australian buyer\'s agent tech stack that compresses property research from 4 hours to 45 minutes — categorised by what each tool does, what it costs, and where it actually moves the needle.',
  },
  {
    slug: 'white-label-building-inspection-report-for-buyers-agents',
    title: 'White-Label Building Inspection Reports for Buyer\'s Agents (Australia, 2026)',
    description: 'How AU buyer\'s agents can deliver branded AS4349.1 building inspection analysis to their clients — what white-label means in property context, what can be branded, what it costs, common pitfalls, and how to set it up.',
    category: 'For buyer\'s agents',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '9 min',
    excerpt: 'Your client uploads their building inspection PDF. Two minutes later they receive a polished defect-by-defect breakdown — with YOUR logo on it, YOUR accent colour, YOUR brand voice. Here\'s how white-label property reports work in 2026, what they cost, and where most agents get the setup wrong.',
  },
  {
    slug: 'lead-paint-pre-1970-australian-homes-buyer-guide',
    title: 'Lead Paint in Pre-1970 Australian Homes: What Building Inspections Catch and What They Miss',
    description: 'Plain-English guide to lead paint in Australian houses built before 1970 — health risk, where it hides, what AS4349.1 inspectors can and can\'t identify, when to test, and remediation costs.',
    category: 'Buyer guide',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '8 min',
    excerpt: 'About 70% of Australian homes built before 1970 contain lead paint somewhere. Your building inspection may flag suspicious paint, but can\'t confirm without lab testing. Most buyers don\'t test — and then renovate without knowing. Here\'s what the actual risk is, what testing costs, and when you should bother.',
  },
  {
    slug: 'how-to-write-builder-rectification-letter-australia',
    title: 'How to Write a Builder Rectification Letter (Australia, 2026) — With Template',
    description: 'Step-by-step guide for Australian new-build owners writing a defects rectification letter to their builder during DLP or PCI. Includes a full ready-to-use template you can copy, edit, and send.',
    category: 'New build',
    published: '2026-05-29',
    updated: '2026-05-29',
    readTime: '10 min',
    excerpt: 'You\'ve identified defects in your new build during practical completion or the defects liability period. The builder is dragging their feet. The fix is a written rectification letter — done correctly, it triggers contractual obligations the builder can\'t ignore. Here\'s the structure that works, plus a full template you can copy.',
  },
  {
    slug: 'strata-report-explained-australia',
    title: 'Strata Report Explained: The Australian Apartment Buyer\'s Guide (2026)',
    description: 'Plain-English breakdown of strata reports / OC certificates / S184 certificates for Australian apartment and unit buyers — what\'s in one, what to look for, state-by-state naming, costs, red flags, and what they don\'t cover.',
    category: 'Buyer guide',
    published: '2026-05-31',
    updated: '2026-05-31',
    readTime: '11 min',
    excerpt: 'You\'re buying an apartment, townhouse, or unit in Australia. Your conveyancer says you need a "strata report." In Victoria it\'s called an Owners Corporation certificate. In NSW it\'s a Section 184 certificate plus a strata records inspection. Most buyers skim it and miss the levy bombshell sitting on page 23. Here\'s exactly what\'s in one, what to look for, and where it falls short.',
  },
  {
    slug: 'concrete-cancer-spalling-cost-australia',
    title: 'Concrete Cancer in Australian Homes: What It Is, What It Costs to Fix (2026)',
    description: 'Plain-English guide to concrete cancer / concrete spalling in Australian houses, balconies and apartments — what the inspector\'s phrases mean, severity levels, real repair costs by scenario, and when to walk vs negotiate.',
    category: 'Buyer guide',
    published: '2026-05-31',
    updated: '2026-05-31',
    readTime: '9 min',
    excerpt: 'Your building inspector wrote "concrete cancer evident to balcony slab" and you stopped reading. It sounds catastrophic. Most of the time it isn\'t — but the cost difference between a cosmetic patch and a structural repair is roughly $3,000 vs $80,000. Here\'s how to tell which one you\'re looking at.',
  },
  {
    slug: 'mould-in-australian-homes-remediation-cost',
    title: 'Mould in Australian Homes: Remediation Cost and What Inspections Miss (2026)',
    description: 'Plain-English guide to mould in Australian houses and apartments — health risk, where it hides, why surface cleaning fails, real remediation costs by severity, and what your AS4349.1 building inspection actually catches.',
    category: 'Buyer guide',
    published: '2026-05-31',
    updated: '2026-05-31',
    readTime: '9 min',
    excerpt: 'Your inspector flagged "mould evident to bathroom ceiling." You\'re wondering if it\'s a deal-breaker or a $300 fix. The honest answer: it depends entirely on the root cause behind it. Visible mould is a symptom — the real question is what\'s feeding it. Here\'s how to triage, what testing costs, and what remediation actually involves.',
  },
];

export function allArticleSlugs() {
  return ARTICLES.map((a) => a.slug);
}

export function getArticle(slug) {
  return ARTICLES.find((a) => a.slug === slug) || null;
}
